"""create proveedores table

Revision ID: 0e5f7dd38b1b
Revises: 13788297e6b9
Create Date: 2026-09-05 17:44:16.221812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5f7dd38b1b'
down_revision: Union[str, Sequence[str], None] = '13788297e6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=150), nullable=False),
    sa.Column('nombre_contacto', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razon_social')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedores')
    # ### end Alembic commands ###
