"""create productos_proveedor table

Revision ID: 0fbce30321c4
Revises: 4d87a41687fc
Create Date: 2026-09-05 18:33:30.664486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbce30321c4'
down_revision: Union[str, Sequence[str], None] = '4d87a41687fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('temporada_id', sa.Integer(), nullable=False),
    sa.Column('coleccion_id', sa.Integer(), nullable=False),
    sa.Column('disponibilidad', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coleccion_id'], ['colecciones.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['temporada_id'], ['temporadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos_proveedor')
    # ### end Alembic commands ###
