"""add proveedor_id to usuarios

Revision ID: 4d87a41687fc
Revises: 0e5f7dd38b1b
Create Date: 2026-09-05 18:18:58.761506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d87a41687fc'
down_revision: Union[str, Sequence[str], None] = '0e5f7dd38b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('proveedor_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['proveedor_id'])
    op.create_foreign_key(None, 'usuarios', 'proveedores', ['proveedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'proveedor_id')
    # ### end Alembic commands ###
