"""add product and category images

Revision ID: 5b8dfdb3e865
Revises: b4bb14c68858
Create Date: 2026-09-05 16:07:25.723974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8dfdb3e865'
down_revision: Union[str, Sequence[str], None] = 'b4bb14c68858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('imagen_url', sa.String(length=500), nullable=True))
    op.add_column('productos', sa.Column('imagen_principal_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'imagen_principal_url')
    op.drop_column('categorias', 'imagen_url')
    # ### end Alembic commands ###
