"""add sucursal_id to usuarios

Revision ID: b3ce5bc51b48
Revises: f7ad01ae1581
Create Date: 2026-09-05 15:11:25.405552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ce5bc51b48'
down_revision: Union[str, Sequence[str], None] = 'f7ad01ae1581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'sucursales', ['sucursal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'sucursal_id')
    # ### end Alembic commands ###
