"""create password reset tokens table

Revision ID: e4429f358af5
Revises: 9eb5b81ebac3
Create Date: 2026-09-11 20:13:57.345836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4429f358af5'
# Apunta al último revision realmente commiteado en main/HEAD
# (add_featured_collection_for_home_hero), NO al último de tu working tree
# local. `d4e8b1f6a2c9` (telefono) y `a7c142f6d9b3` (stock_sucursal,
# GestionStockSucursal) todavía no están commiteados en ninguna rama, y
# password_reset_tokens no depende de ninguno de los dos (solo referencia
# usuarios.id) -- encadenar CU03 a ellos acoplaría esta rama a otros CU sin
# necesidad y rompería `alembic upgrade head` en un clon limpio de
# feature/CU03-recuperar-contrasena.
down_revision: Union[str, Sequence[str], None] = '9eb5b81ebac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_usuario_id'), 'password_reset_tokens', ['usuario_id'], unique=False)
    # NOTA: el autogenerate también detectó un drop de 'ix_colecciones_una_destacada_inicio'
    # (drift de CU10, ajeno a CU03) -- se omite deliberadamente para no tocar
    # catálogo/colecciones desde esta migración.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_usuario_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
