"""add departamento to ciudades

Revision ID: f7ad01ae1581
Revises: 3d7f67e9a3e7
Create Date: 2026-09-05 14:46:23.862910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ad01ae1581'
down_revision: Union[str, Sequence[str], None] = '3d7f67e9a3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Se agrega nullable primero porque ya existen filas (Santa Cruz, Cochabamba,
    # La Paz, sembradas por scripts/seed_ciudades.py); se completan con el propio
    # nombre (coincide con su departamento) antes de exigir NOT NULL.
    op.add_column('ciudades', sa.Column('departamento', sa.String(length=120), nullable=True))
    op.execute("UPDATE ciudades SET departamento = nombre WHERE departamento IS NULL")
    op.alter_column('ciudades', 'departamento', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ciudades', 'departamento')
    # ### end Alembic commands ###
